contact_links:
  - name: Доложить о уязвимости в системе безопасности
    url: https://github.com/ss14-ganimed/Ganimed-station/security/policy
    about: Пожалуйста, сообщайте об уязвимостях в системе безопасности в личные сообщения, чтобы мы могли устранить их до того, как они станут достоянием общественности.
  - name: Запросите добавление вашего приложения
    url: https://discord.gg/YWp7dkMDTG
    about: Отправьте своё приложение/бота на рассмотрение в наш дискорд (https://discord.gg/YWp7dkMDTG).
